package net;

import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Authenticator;
import java.net.HttpURLConnection;
import java.net.InetAddress;
import java.net.PasswordAuthentication;
import java.net.URL;
import java.net.URLConnection;
import java.net.UnknownHostException;

/**
 * @author Mateusz Rusnaczyk
 *
 */
public class ConnectionManager {
	LoginDialog auth;
	PasswordAuthentication a;

	public ConnectionManager() {
		System.setProperty("http.agent", "SimpleSync/0.0.1 (Windows)");
		// auth = new LoginDialog();
		// Authenticator.setDefault(auth);
		// Authenticator.requestPasswordAuthentication("",
		// InetAddress.getByName("cs.rusnaczyk.tk"), 80, "", "", "");

	}

	/**
	 * Returns an authentication token for the client to use to sync files. This
	 * method requires that the user have supplied valid credentials
	 * 
	 * @return An authentication token as a char array
	 */
	public char[] getKey() {
		// Add throws exception
		// a = auth.getPasswordAuthentication();
		URL url;
		URLConnection conn;
		char[] key = null;
		String k = "";
		try {
			url = new URL("http", "cs.rusnaczyk.tk", "/SimpleSync/genKey.php");
			conn = url.openConnection();
			InputStreamReader in = new InputStreamReader(conn.getInputStream());
			int c;
			while ((c = in.read()) != -1) {
				k += (char) c;
			}
			key = k.toCharArray();
			k = null;
		} catch (IOException e) {
			e.printStackTrace();
		}

		return key;

	}

	/**
	 * Revokes a key generated by {@link getKey()}
	 * 
	 * <p>
	 * This method should be called after an object no longer needs the
	 * authentication key it received from {@link getKey()}
	 * </p>
	 * 
	 * @param key
	 *            The authentication key to be revoked
	 */
	public void revokeKey(String key) {
		// Add throws exception
	}
}
